// assets/js/commons/components/dialogs/content/PaymentSucceed.svelte
<script lang="ts">
  export let translations:any = {
    text:""
  }

  export let redirectUrl:string
  
</script>
<div class="payment-failure">
  <div class="grid grid-cols-[min-content,1fr] gap-4">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-16 h-16 fill-green-400">
      <path fill-rule="evenodd" d="M2.25 12c0-5.385 4.365-9.75 9.75-9.75s9.75 4.365 9.75 9.75-4.365 9.75-9.75 9.75S2.25 17.385 2.25 12Zm13.36-1.814a.75.75 0 1 0-1.22-.872l-3.236 4.53L9.53 12.22a.75.75 0 0 0-1.06 1.06l2.25 2.25a.75.75 0 0 0 1.14-.094l3.75-5.25Z" clip-rule="evenodd" />
    </svg>
    
    <div class="flex flex-col gap-2">
      <p class="text-2xl font-extrabold">{translations.title}</p>
      <p>{translations.text}</p>
    </div>
    
    
  </div>
  <div class="flex justify-end gap-4">
    <a class="btn btn-primary rounded-md" href={redirectUrl}>Continue</a>
  </div>
  
  
</div>

<style>
  .payment-failure {

    width: 100%;
    display: grid;
    justify-content: flex-start;
    align-items: flex-start;
    grid-template-columns: 1fr;
    gap:10px;

}





</style>

// applications/apps/checkout/src/components/views/payment-succeed.tsx
import { useCheckout } from "./../../providers/checkout-provider";
import React from "react";

export const PaymentSucceed = () => {

  const {config} = useCheckout()

  return (
    <div className="flex flex-col justify-center gap-8 bg-white p-4">
      <div className="flex-col md:grid md:grid-cols-[min-content,1fr] justify-start gap-4">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
          className="lucide lucide-badge-check w-16 h-16 fill-green-400 stroke-white hidden md:block"
        >
          <path d="M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76Z" />
          <path d="m9 12 2 2 4-4" />
        </svg>

        <div className="flex flex-col gap-4 ">
          <div>
            <div className="flex flex-col md:flex-row items-center">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
                className="lucide lucide-circle-x w-16 h-16 fill-green-400 stroke-white block md:hidden"
              >
                <path d="M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76Z" />
                <path d="m9 12 2 2 4-4" />
              </svg>

              <span className="text-2xl font-bold text-green-400">Payment succeed</span>
            </div>
          </div>
          <div>
            <p>
              Thank you! You order is on the way. You can now view your order or close this window safely.  
            </p>
          </div>
        </div>
      </div>
      <div className="flex flex-col md:flex-row justify-end gap-4">
        <a href={ config?.wooThankYouUrl} className="p-2 bg-purple-600 rounded-md font-bold text-white ">
          Continue
        </a>
      </div>
    </div>
  );
};
